<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Ampela',
                'slug' => 'ampela-1780389026',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Ampela ayam segar yang telah dibersihkan sempurna, cocok untuk diolah menjadi hidangan sambal goreng atau tumisan yang lezat dan bertekstur kenyal.',
                'price' => 44000,
                'sold' => 0,
                'image' => '1780389026_ampela.jpg',
                'stock' => 100,
                'created_at' => '2026-06-02 08:30:26',
                'updated_at' => '2026-06-02 08:30:26',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Ayam Utuh',
                'slug' => 'ayam-utuh-1780390129',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Satu ekor ayam utuh segar pilihan yang cocok untuk berbagai jenis masakan keluarga seperti ayam panggang, ayam kodok, maupun kaldu berlimpah.',
                'price' => 57500,
                'sold' => 0,
                'image' => '1780389507_ayamutuh.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:38:27',
                'updated_at' => '2026-06-02 08:48:49',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Boneless Dada Skinless',
                'slug' => 'boneless-dada-skinless-1780389557',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Potongan daging dada ayam tanpa tulang dan tanpa kulit, tinggi protein dan rendah lemak, sangat ideal untuk menu diet sehat atau olahan tumisan.',
                'price' => 79000,
                'sold' => 0,
                'image' => '1780389557_bldadasl.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:39:17',
                'updated_at' => '2026-06-02 08:39:17',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Boneless Paha',
                'slug' => 'boneless-paha-1780389624',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Daging paha ayam tanpa tulang yang masih memiliki kulit, menawarkan tekstur daging yang lebih juicy dan gurih untuk hidangan sate, teriyaki, atau ayam goreng tepung.',
                'price' => 78000,
                'sold' => 0,
                'image' => '1780389624_blpaha.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:40:24',
                'updated_at' => '2026-06-02 08:40:24',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Boneless Paha Cut',
                'slug' => 'boneless-paha-cut-1780389670',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Potongan daging paha tanpa tulang yang sudah dipotong kecil-kecil, sangat praktis dan siap masak untuk masakan sehari-hari tanpa perlu repot memotong lagi.',
                'price' => 78000,
                'sold' => 0,
                'image' => '1780389670_blpahacuts.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:41:10',
                'updated_at' => '2026-06-02 08:41:26',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Boneless Paha Skinless',
                'slug' => 'boneless-paha-skinless-1780389799',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Daging paha ayam tanpa tulang dan tanpa kulit yang tetap mempertahankan tekstur juicy khas paha, menjadikannya pilihan sehat yang kaya rasa.',
                'price' => 78000,
                'sold' => 0,
                'image' => '1780389799_blpahasl.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:43:19',
                'updated_at' => '2026-06-02 08:43:19',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ceker Bersih',
                'slug' => 'ceker-bersih-1780389866',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Ceker ayam segar yang sudah dibersihkan dari kuku dan kulit luarnya, siap diolah menjadi seblak, sup, atau dimsum ceker yang empuk dan kaya kolagen.',
                'price' => 44000,
                'sold' => 0,
                'image' => '1780389866_cekerbersih.jpg',
                'stock' => 100,
                'created_at' => '2026-06-02 08:44:26',
                'updated_at' => '2026-06-02 08:48:59',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Cut 10',
                'slug' => 'cut-10-1780390293',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Satu ekor ayam utuh yang telah dipotong rapi menjadi 10 bagian, sangat praktis untuk kebutuhan masak harian seperti ayam goreng atau gulai tanpa perlu memotong sendiri.',
                'price' => 58500,
                'sold' => 0,
                'image' => '1780390293_cut10.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:51:33',
                'updated_at' => '2026-06-02 08:51:33',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Cut 10 Ori',
                'slug' => 'cut-10-ori-1780390405',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin, Tanpa MSG',
                'description' => 'Potongan ayam 10 bagian dengan bumbu original murni yang dijamin tanpa MSG, memberikan rasa gurih alami yang aman dan sehat untuk dikonsumsi seluruh keluarga.',
                'price' => 72500,
                'sold' => 0,
                'image' => '1780390405_cut10ori.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:53:25',
                'updated_at' => '2026-06-06 14:24:22',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Dada Utuh',
                'slug' => 'dada-utuh-1780390565',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
            'description' => 'Bagian dada ayam utuh (dengan tulang) yang memiliki daging tebal, sangat pas untuk dibuat kaldu jernih sekaligus disuwir untuk soto atau bubur ayam.',
                'price' => 73000,
                'sold' => 0,
                'image' => '1780390565_dadautuh.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 08:56:05',
                'updated_at' => '2026-06-02 08:56:05',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Hati',
                'slug' => 'hati-1780390695',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Hati ayam segar bernutrisi tinggi yang kaya akan zat besi, sangat baik untuk menu MPASI anak atau dimasak menjadi sambal goreng ati yang menggugah selera.',
                'price' => 44000,
                'sold' => 0,
                'image' => '1780390695_hati.jpg',
                'stock' => 100,
                'created_at' => '2026-06-02 08:58:15',
                'updated_at' => '2026-06-06 14:24:22',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Jantung',
                'slug' => 'jantung-1780390764',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Jantung ayam segar dengan tekstur kenyal yang khas, sangat cocok untuk dijadikan menu sate jantung atau campuran dalam masakan tumis pedas manis.',
                'price' => 44000,
                'sold' => 0,
                'image' => '1780390764_jantung.jpg',
                'stock' => 100,
                'created_at' => '2026-06-02 08:59:24',
                'updated_at' => '2026-06-05 01:20:49',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Paha Atas',
                'slug' => 'paha-atas-1780390855',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Potongan paha atas ayam yang memiliki rasio daging tebal dan tekstur sangat juicy, ideal untuk ayam bakar, ungkep, atau masakan berkuah kental.',
                'price' => 67500,
                'sold' => 0,
                'image' => '1780390855_pahaatas.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:00:55',
                'updated_at' => '2026-06-08 05:07:18',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Paha Bawah',
                'slug' => 'paha-bawah-1780390890',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
            'description' => 'Potongan paha bawah (drumstick) yang paling disukai anak-anak, sangat pas untuk digoreng crispy atau dijadikan hidangan ayam kecap yang bumbunya meresap.',
                'price' => 67500,
                'sold' => 0,
                'image' => '1780390890_pahabawah.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:01:30',
                'updated_at' => '2026-06-08 14:34:32',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Paha Cut Ori',
                'slug' => 'paha-cut-ori-1780390948',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin, Tanpa MSG',
                'description' => 'Potongan praktis paha ayam berbumbu original murni tanpa MSG, menghadirkan cita rasa gurih alami yang lezat, sehat, dan langsung siap untuk dimasak kapan saja.',
                'price' => 91000,
                'sold' => 0,
                'image' => '1780390948_pahacutori.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:02:28',
                'updated_at' => '2026-06-08 14:34:32',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Paha Utuh',
                'slug' => 'paha-utuh-1780391001',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
            'description' => 'Potongan paha utuh (gabungan paha atas dan bawah) yang besar dan memuaskan, sangat cocok untuk hidangan utama seperti ayam bakar madu atau ayam goreng kalasan.',
                'price' => 67500,
                'sold' => 0,
                'image' => '1780391001_pahautuh.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:03:21',
                'updated_at' => '2026-06-08 15:13:12',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Sayap',
                'slug' => 'sayap-1780391042',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
                'description' => 'Potongan sayap ayam segar dengan tekstur kulit yang kenyal dan daging gurih, pilihan tepat untuk membuat spicy chicken wings atau hidangan camilan.',
                'price' => 62000,
                'sold' => 0,
                'image' => '1780391042_sayap.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:04:02',
                'updated_at' => '2026-06-08 11:09:53',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Tenderloin',
                'slug' => 'tenderloin-1780391837',
                'category' => 'Ayam Probiotik',
                'weight' => '900 - 1.000 gram',
                'advantages' => 'Bebas Residu Antibiotik, Bebas Suntik Hormon Pertumbuhan, Bebas Flu Burung, Bebas Formalin',
            'description' => 'Bagian daging ayam paling empuk (fillet dalam), sangat cepat matang dan bertekstur halus, sempurna untuk hidangan katsu premium atau chicken strips.',
                'price' => 82000,
                'sold' => 0,
                'image' => '1780391837_tenderloin.jpg',
                'stock' => 50,
                'created_at' => '2026-06-02 09:17:17',
                'updated_at' => '2026-06-08 11:08:13',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Telur Ayam Omega-3',
                'slug' => 'telur-ayam-omega-3-1780810543',
                'category' => 'Telur Organik',
                'weight' => '600 - 650 gram',
                'advantages' => 'Bebas Residu Antibiotik, Omega-3, Herbal Essential, Antioksidan',
            'description' => 'Telur Ayam Omega-3 premium pilihan yang dihasilkan dari peternakan organik terstandar. Diperkaya dengan pakan Herbal Essential, telur ini tidak hanya tinggi kandungan Omega-3 dan Antioksidan, tetapi juga dijamin 100% Bebas Residu Antibiotik. Pilihan yang jauh lebih sehat, aman, dan bergizi untuk penuhi kebutuhan protein harian keluarga Anda. (1 Pack isi 10 butir).',
                'price' => 50000,
                'sold' => 0,
                'image' => '1780810543_teluromega.png',
                'stock' => 20,
                'created_at' => '2026-06-07 05:35:43',
                'updated_at' => '2026-06-08 14:46:13',
            ),
        ));
        
        
    }
}